#!/bin/bash
echo "Deploy to Docker BETA server..."
export NODE_ENV=production
NODE_ENV=production gulp
cd dist
cp ../.env .
cp ../.static .
export NODE_ENV=development
git init
git remote add deploy dokku@athina.med.duth.gr:carre-entry-system-beta
git add .
git commit -am"deploy"
git push -f deploy master