#!/bin/bash

export NODE_ENV=production
export CARRE_ENTRY_SYSTEM_LANGUAGE=en
export CARRE_ENTRY_SYSTEM_API_URL=https://carre.kmi.open.ac.uk/ws/
export CARRE_ENTRY_SYSTEM_AUTH_URL=https://devices.carre-project.eu/devices/accounts/
export CARRE_ENTRY_SYSTEM_GRAPH_URL=http://carre.kmi.open.ac.uk/
#gulp build

git checkout default-docker && git rm -r * && git add dist && git add Dockerfile && git add package.json && git add .dockerignore && git add server
git commit -m"new image version"
git push -f origin default-docker

