#!/bin/bash
echo "deploy changes"
cd dist
git init
git remote add docker git@github.com:carre-project/carre-entry-system-docker.git
git remote add deploy dokku@athina.med.duth.gr:carre-entry-system
git add .
git commit -am"update distribution"
git push -f deploy master
git push -f docker master
cd ..